const sampleCategories = [
  { name: 'Electronics & Laptops', slug: 'electronics', description: 'High-performance laptops, smartphones, & gadgets', icon: 'Laptop' },
  { name: 'Audio & Wearables', slug: 'audio', description: 'Wireless headphones, smartwatches & speakers', icon: 'Headphones' },
  { name: 'Apparel & Footwear', slug: 'apparel', description: 'Premium sneakers, activewear & fashion', icon: 'Shirt' },
  { name: 'Home & Living', slug: 'home', description: 'Smart appliances & modern home decor', icon: 'Home' },
];

const sampleProducts = [
  {
    _id: '650000000000000000000001',
    name: 'MacBook Air M3 Pro Edition',
    description: 'Ultra-thin, blistering performance with Apple M3 chip, 16GB Unified Memory, 512GB SSD, 15.3-inch Liquid Retina Display.',
    price: 114900,
    originalPrice: 129900,
    category: 'Electronics & Laptops',
    brand: 'Apple',
    stock: 15,
    images: ['https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=800'],
    isFeatured: true,
    rating: 4.9,
    numReviews: 48,
    specifications: { Display: '15.3-inch Retina', Processor: 'Apple M3 8-Core', RAM: '16GB', Storage: '512GB SSD', Weight: '1.51 kg' },
    advantages: ['Superb battery life up to 18 hours', 'Silent fanless design', 'Vibrant Liquid Retina screen'],
    disadvantages: ['Limited port selection', 'No touch screen'],
    tags: ['laptop', 'apple', 'macbook', 'programming'],
  },
  {
    _id: '650000000000000000000002',
    name: 'Asus ROG Strix Gaming Laptop',
    description: 'NVIDIA GeForce RTX 4060, Intel Core i7-13650HX, 16GB DDR5, 1TB SSD, 165Hz FHD Gaming Display.',
    price: 68990,
    originalPrice: 79990,
    category: 'Electronics & Laptops',
    brand: 'ASUS',
    stock: 8,
    images: ['https://images.unsplash.com/photo-1603302576837-37561b2e2302?w=800'],
    isFeatured: true,
    rating: 4.7,
    numReviews: 32,
    specifications: { Display: '15.6-inch 165Hz', GPU: 'RTX 4060 8GB', RAM: '16GB DDR5', Storage: '1TB NVMe SSD' },
    advantages: ['High refresh rate display', 'Dedicated RTX graphics', 'RGB Aura Sync keyboard'],
    disadvantages: ['Slightly heavier chassis', 'Shorter battery life under load'],
    tags: ['gaming', 'laptop', 'asus', 'rtx'],
  },
  {
    _id: '650000000000000000000003',
    name: 'Sony WH-1000XM5 Wireless Headphones',
    description: 'Industry-leading noise canceling with two processors, 8 microphones, 30-hour battery life, and crystal clear hands-free calling.',
    price: 26990,
    originalPrice: 34990,
    category: 'Audio & Wearables',
    brand: 'Sony',
    stock: 25,
    images: ['https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=800'],
    isFeatured: true,
    rating: 4.8,
    numReviews: 89,
    specifications: { Connectivity: 'Bluetooth 5.2', Battery: '30 Hours', NoiseCanceling: 'Active Dual Chip', Weight: '250g' },
    advantages: ['Top-tier active noise cancellation', 'Extremely comfortable ear pads', 'Quick charge 3 min = 3 hrs playback'],
    disadvantages: ['Does not fold completely compact'],
    tags: ['audio', 'headphones', 'sony', 'noise canceling'],
  },
  {
    _id: '650000000000000000000004',
    name: 'Nike ZoomX Vaporfly Running Shoes',
    description: 'Engineered for marathons and fast road racing with responsive carbon fiber plate and ultra-light ZoomX foam.',
    price: 2899,
    originalPrice: 4999,
    category: 'Apparel & Footwear',
    brand: 'Nike',
    stock: 40,
    images: ['https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=800'],
    isFeatured: true,
    rating: 4.6,
    numReviews: 64,
    specifications: { Upper: 'Flyknit Breathable Mesh', Midsole: 'ZoomX Foam + Carbon Plate', Sole: 'Rubberized Traction' },
    advantages: ['Exceptional energy return', 'Lightweight breathable mesh', 'Unmatched propulsion feel'],
    disadvantages: ['Designed primarily for racing surfaces'],
    tags: ['shoes', 'running', 'nike', 'footwear'],
  },
  {
    _id: '650000000000000000000005',
    name: 'Samsung Galaxy Watch 6 Pro',
    description: 'Advanced sleep tracking, personalized HR zone monitoring, sapphire crystal glass, bioelectrical impedance sensor.',
    price: 21999,
    originalPrice: 29999,
    category: 'Audio & Wearables',
    brand: 'Samsung',
    stock: 18,
    images: ['https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=800'],
    isFeatured: false,
    rating: 4.5,
    numReviews: 21,
    specifications: { Screen: '1.5-inch Super AMOLED', Battery: '425mAh', WaterResistance: '5ATM + IP68' },
    advantages: ['Robust titanium casing', 'Comprehensive body composition analytics', 'Seamless Android integration'],
    disadvantages: ['Best paired with Samsung phones'],
    tags: ['watch', 'smartwatch', 'samsung', 'fitness'],
  },
];

const sampleCoupons = [
  { code: 'SAVE10', discountPercentage: 10, maxDiscountAmount: 2000, minPurchaseAmount: 1000, isActive: true },
  { code: 'WELCOME20', discountPercentage: 20, maxDiscountAmount: 3000, minPurchaseAmount: 1500, isActive: true },
];

module.exports = { sampleCategories, sampleProducts, sampleCoupons };
